server:
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: 'app_logs'
    static_configs:
      - targets:
          - localhost
        labels:
          job: app
          __path__: C:/Users/acer/OneDrive/Desktop/intuji/docker-with-monitoring/nodelog/*.log

      - targets:
          - localhost
        labels:
          job: db
          __path__: C:/Users/acer/OneDrive/Desktop/intuji/docker-with-monitoring/dblog/*.log
