version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=raju
      - POSTGRES_PASSWORD=raju@123
      - POSTGRES_DB=backend_v12
      - NODE_ENV=development
    depends_on:
      - db
    volumes:
      - .:/app
      - ./nodelog:/path/to/logs:/var/log

    networks:
      - my_network
    labels:
      - "prometheus_job=app"

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      - POSTGRES_USER=raju
      - POSTGRES_PASSWORD=raju@123
      - POSTGRES_DB=backend_v12
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
      - ./dblog:/var/log
    networks:
      - my_network


  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./yml/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - my_network
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  loki:
    image: grafana/loki
    container_name: loki
    ports:
      - "3100:3100"
    networks:
      - my_network

  promtail:
    image: grafana/promtail:2.7.1
    container_name: promtail
    networks:
      - my_network
    volumes:
      - ./yml/promtail-config.yaml:/etc/promtail/config.yaml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro 
      - /var/log:/var/log:ro 
    command: -config.file=/etc/promtail/config.yaml
    depends_on:
      - loki

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - my_network
    depends_on:
      - prometheus
      - loki
    volumes:
      - grafana_data:/var/lib/grafana

  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
    networks:
      - my_network

volumes:
  postgres_data:
  grafana_data:
  loki-data:

networks:
  my_network:
